name: 'build'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: ghcr.io/ugns/geodesic
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          addLatest: true
 
